"""empty message

Revision ID: ed46b992fa5b
Revises: 859ef82b49b9
Create Date: 2025-08-14 00:55:46.502000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed46b992fa5b'
down_revision = '859ef82b49b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.INTEGER(),
               type_=sa.Enum('image', 'video', name='media_types'),
               existing_nullable=False)
        batch_op.drop_constraint('media_type_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.create_foreign_key('media_type_fkey', 'user', ['type'], ['id'])
        batch_op.alter_column('type',
               existing_type=sa.Enum('image', 'video', name='media_types'),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
